version: '3'

env:
  ENV: development

dotenv: ['.env', '.env.{{.ENV}}']

tasks:
  startUp:
    deps: [composeUp]
    cmds:
      - dbmate up
      - pnpm hasura metadata apply
      - pnpm prisma:generate

  hasura:
    cmds:
      - hasura --project ./hasura --skip-update-check {{.CLI_ARGS}}

  migrateUp:
    cmds:
      - dbmate up

  migrateDown:
    cmds:
      - dbmate down

  prismaPull:
    cmds: 
      - pnpm prisma db pull
      
  composeUp:
    cmds:
      - docker-compose --env-file ./.env.development up -d

  composeDown:
    cmds:
      - docker-compose --env-file ./.env.development down --remove-orphans
  
  dockerBuild:
    cmds: 
      - DOCKER_BUILDKIT=1 docker build -f Dockerfile --build-arg SCOPE="backend" --build-arg FOLDER="backend" --build-arg PORT=6000 --tag youtube-clone/backend .
