version: '3'

env:
  ENV: development

dotenv: ['.env', '.env.{{.ENV}}']

tasks:
  migrateUp:
    cmds:
      - dbmate up
      - hasura metadata reload

  migrateDown:
    cmds:
      - dbmate down

  prismaPull:
    cmds: 
      - pnpm prisma db pull
      
  composeUp:
    cmds:
      - docker-compose --env-file ./.env.development up

  composeDown:
    cmds:
      - docker-compose --env-file ./.env.development down --remove-orphans
